name: AWS Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::473123644309:role/github-actions-exchange
          aws-region: us-east-1

      - name: Check AWS identity
        run: aws sts get-caller-identity
